### ISSUE TITLE
支持用户登录后获取NSFW内容|| Support access to NSFW content after logging in with username and password along with possible verification code

### ISSUE THREAD

**Issue by hegotit** [monkeyWie/gopeed-extension-twitter#1]
目前下载NSFW内容需要cookie，在移动端操作不方便，能否直接登录用户以获取访问权限？

Currently, a cookie is required for access to NSFW content, which is inconvenient on mobile, so is it possible to log in to obtain access permissions?

**Comment by monkeyWie** [comment]
可以加个Cookie选项配置

**Comment by monkeyWie** [comment]
Please upgrade to v1.1.0
