### ISSUE TITLE
[iOS Issue] Cannot install extensions

### ISSUE THREAD

**Issue by korboybeats** [monkeyWie/gopeed-extension-twitter#4]
https://github.com/monkeyWie/gopeed-extension-twitter/assets/80824905/86eb5700-7a5c-461d-90da-c8ffb644eb50

Error
Get "https://github.com/monkeyWie/gopeed-extension-twitter.git/info/refs?service=git-upload-pack": dial tcp: lookup
github.com on [::1]:53: read udp [:1]:51009->[::1]:53: read: 
connection refused

**Comment by monkeyWie** [comment]
please update gopeed to v1.5.7
